(autoload 'hide-lines                           "hide-lines" "" t)
(autoload 'add-invisible-overlay                "hide-lines" "" nil)
(autoload 'hide-non-matching-lines              "hide-lines" "" t)
(autoload 'hide-matching-lines                  "hide-lines" "" t)
(autoload 'show-all-invisible                   "hide-lines" "" t)
(provide 'hide-lines-epkg-autoloads)
